name: Homelab DNS Records

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./homelab_domain

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.3

    - name: Setup Terraform CLI  
      uses: hashicorp/setup-terraform@v3

    - name: Run Terraform Init
      run: terraform init

    - name: Run Terraform Plan
      run: terraform plan -out ${{github.run_id}}.tfplan

  
    